export const heroIcons = [
  {
    name: 'angular',
    img: '/assets/icon_angular_logo.svg',
    size: 46,
    position: { x: 230, y: 350 },
  },
  {
    name: 'firebase',
    img: '/assets/icon_firebase_logo.svg',
    size: 48,
    position: { x: -390, y: 310 },
  },
  {
    name: 'git',
    img: '/assets/icon_git_logo.svg',
    size: 36,
    position: { x: -360, y: -20 },
  },
  {
    name: 'ionic',
    img: '/assets/icon_ionic_logo.svg',
    size: 31,
    position: { x: 215, y: -60 },
  },
  {
    name: 'react',
    img: '/assets/icon_react_logo.svg',
    size: 45,
    position: { x: 390, y: 170 },
  },
  {
    name: 'typescript',
    img: '/assets/icon_typescript_logo.svg',
    size: 33,
    position: { x: -290, y: 140 },
  },
];

export const workList = [
  {
    type: 'web',
    name: 'Streaum',
    mainImg: '/assets/worksImages/img_streaum.png',
    desc: '스트리머 팬덤 기반 게임 랭크 사이트',
    year: '2024',
    skill: [
      'React',
      'vite',
      'zustand',
      'Restful Api',
      'React Query',
      'Electron',
      'Recharts',
      'React quill',
      'Storybook',
      'FramerMotion',
    ],
    keyFeatures: [
      '랭킹',
      '커뮤니티',
      '유튜브 api 연결',
      '스트리밍 플랫폼 api 연결',
      '주요 게임 api 연결',
    ],
    design: ['Figma'],
  },
  {
    type: 'app',
    name: 'ANIDAR',
    mainImg: '/assets/worksImages/img_anidar.png',
    desc: '스트리머 팬덤 기반 게임 랭크 사이트',
    year: '2022',
    skill: ['Ionic', 'Angular', 'Firebase', 'Capacitor'],
    keyFeatures: ['예약기능', 'QR', '쇼핑몰', 'push 알람', '채팅'],
    design: ['Sketch'],
  },
  {
    type: 'web',
    name: 'StartApp 메인 홈페이지',
    mainImg: '/assets/worksImages/img_startapp.png',
    desc: '스트리머 팬덤 기반 게임 랭크 사이트',
    year: '2022',
    skill: ['Angular', 'Firebase'],
    keyFeatures: ['문의하기', '간편 견적', '견적 다운'],
    design: ['Sketch'],
  },
  {
    type: 'app',
    name: 'Heyo',
    mainImg: '/assets/worksImages/img_heyo.png',
    desc: '스트리머 팬덤 기반 게임 랭크 사이트',
    year: '2022',
    skill: ['Ionic', 'Angular', 'Firebase', 'cordova'],
    keyFeatures: [
      '지역기반',
      '커뮤니티',
      '포인트 차감',
      '실명 인증',
      '번호 인증',
      'push 알람',
    ],
    design: [],
  },
  {
    type: 'app',
    name: 'Heyo',
    mainImg: '/assets/worksImages/img_heyo.png',
    desc: '스트리머 팬덤 기반 게임 랭크 사이트',
    year: '2022',
    skill: ['Ionic', 'Angular', 'Firebase', 'cordova'],
    keyFeatures: [
      '지역기반',
      '커뮤니티',
      '포인트 차감',
      '실명 인증',
      '번호 인증',
      'push 알람',
    ],
    design: [],
  },
  {
    type: 'app',
    name: 'Heyo',
    mainImg: '/assets/worksImages/img_heyo.png',
    desc: '스트리머 팬덤 기반 게임 랭크 사이트',
    year: '2022',
    skill: ['Ionic', 'Angular', 'Firebase', 'cordova'],
    keyFeatures: [
      '지역기반',
      '커뮤니티',
      '포인트 차감',
      '실명 인증',
      '번호 인증',
      'push 알람',
    ],
    design: [],
  },
  {
    type: 'app',
    name: 'Heyo',
    mainImg: '/assets/worksImages/img_heyo.png',
    desc: '스트리머 팬덤 기반 게임 랭크 사이트',
    year: '2022',
    skill: ['Ionic', 'Angular', 'Firebase', 'cordova'],
    keyFeatures: [
      '지역기반',
      '커뮤니티',
      '포인트 차감',
      '실명 인증',
      '번호 인증',
      'push 알람',
    ],
    design: [],
  },
];

export const frontEndSkill = [
  'React',
  'Angular',
  'Next.js',
  'JavaScript',
  'TypeScript',
  'WordPress',
  'Electron',
  'Capacitor',
  'Cordova',
  'Firebase ',
  'Zustand',
  'React Query',
  'Chart.js',
  'Recharts',
  'React quill',
];

export const workToolsSkill = [
  'HTML',
  'CSS',
  'SCSS',
  'Tailwindcss',
  'GitHub',
  'GitLab',
  'Figma',
  'Photoshop',
  'XD',
  'Sketch',
  'Storybook',
];
